---
title: "kMeans"
author: "inryeol"
date: "2024-08-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```


```{r}
# 데이터 준비 & plot 그리기 
rm(list=ls())
set.seed(1234)
x = rnorm(12, mean=rep(1:3, each=4), sd=0.2)
y = rnorm(12, mean = rep(c(1, 2, 1), each=4),
          sd=0.2)
plot(x, y, col="blue", cex=2, pch=19)
text(x+0.05, y+0.05, as.character(1:12))
```
```{r}
# kmeans() 써보기
library(stats)
dataFrame = data.frame(x, y)
kmeans_obj = kmeans(dataFrame, centers=3, iter.max=100)
names(kmeans_obj)
kmeans_obj$cluster
```
```{r}
# 최종결과
plot(x, y, col=kmeans_obj$cluster, cex=2, pch=19)
points(kmeans_obj$centers, pch=3, cex=2)
```
```{r}
# 히트맵 - 데이터 준비
set.seed(1234)
datamat = as.matrix(dataFrame)[sample(1:12),]
kmeans_obj = kmeans(datamat, centers=3)
```
```{r}
# 히트맵 만들기 1
library(gplots)
par(mfrow=c(1,2))
```
```{r}
# density.info = none
heatmap.2(datamat, trace='none', notecol = 'black', density.info = 'none', dendrogram="none")
```
```{r}
# 클러스터 평가하기
library(cluster)

data.dist = dist(datamat)
data.km2 = kmeans(datamat, centers=2)
data.km3 = kmeans(datamat, centers=3)
data.km4 = kmeans(datamat, centers=4)
```

```{r}
data.km2.sil = silhouette(data.km2$cluster, data.dist)
```

```{r}
plot(data.km2.sil)
```

```{r}
heatmap.2(, trace='none', notecol = 'black', density.info = 'none', dendrogram="none")
```
```{r}
# 히트맵 만들기 2
par(mfrow=c(1,2))
image(t(datamat)[, nrow(datamat):1], yaxt="n", main="original data")
image(t(datamat)[, order(kmeans_obj$cluster)], yaxt="n", main="clustered data")
```
```{r}
# 사각형 씌우기
plot(hcluster)
rect.hclust(hcluster, k=2)
```
```{r}
plot(hcluster)
rect.hclust(hcluster, k=4)
```
```{r}
# 실루엣 통계량 만들기
library(cluster)
data.dist = dist(datamat)
data.km2 = kmeans(datamat, centers=2)
data.km3 = kmeans(datamat, centers=3)
data.km4 = kmeans(datamat, centers=4)
```
```{r}
data.km2.sil = silhouette(data.km2$cl, data.dist)
data.km3.sil = silhouette(data.km3$cl, data.dist)
data.km4.sil = silhouette(data.km4$cl, data.dist)
```
```{r}
par(mfrow=c(1, 3))
plot(data.km2.sil)
plot(data.km3.sil)
plot(data.km4.sil)
```
