---
title: "hCluster"
author: "inryeol"
date: "2024-08-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

# 개요 : 계층적 군집분석

-   hiercial clustering, 줄여서 hclustering 이라고 함. (한국어로 계보적/계층적 군집분석이라고 함.)
-   고차원의 데이터를 시각화할 때 사용하는 방법
-   요점은 가까이에 있는 대상들을 묶어서 그룹으로 만드는 것.
-   다음과 같은 질문을 던질 수 있다.
    -   `가깝다`를 어떻게 정의할 것인가?
    -   어떻게 묶을 것인가?
    -   그룹을 어떻게 시각화할 것인가?
    -   어떻게 그룹을 해석할 것인가?

# 예시 1

## 데이터 생성

> 데이터를 만들어주고, 시뮬레이션을 수행.

```{r}
set.seed(1234)
x = rnorm(12, rep(1:3, each=4), 0.2)
y = rnorm(12, rep(c(1, 2, 1), each=4), 0.2)
plot(x, y, col="blue", pch=19, cex=2)
text(x + 0.05, y + 0.05, labels=as.character(1:12))
```

## 거리행렬 
> 거리행렬을 구해보자.

```{r}
# 거리행렬 만들기
dataFrame = data.frame(x=x, y=y)

# 행렬로 만들기
rdist_xy = as.matrix(dist(dataFrame))

# 최솟값인 대각원소 없애주기
diag(rdist_xy) = diag(rdist_xy) + 100000
```

> 추가적으로 가장 가까운 점을 표기해보자.

```{r}
# 가장 가까운 점
ind1 = which(rdist_xy == min(rdist_xy), arr.ind=TRUE)
ind1

# 그래프 그리기
plot(x, y, col="blue", cex=2, pch=19)
text(x + 0.05, y + 0.05, as.character(1:12))
points(x[ind1[1, ]], y[ind1[1, ]], col="orange", cex=2, pch=19)
```

## 덴드로그램 (1)

> 덴드로그램 만들기

```{r}
# 덴드로그램 만들기
hcluster = hclust(dist(dataFrame))
dendro = as.dendrogram(hcluster)

# 덴드로그램 자르기
cutDendro = cut(dendro, h=(hcluster$height[1] + 0.00001))

# 덴드로그램만 그리기
cutDendro$lower
plot(cutDendro$lower[[11]], yaxt="n", main="Begin building tree")

# 플롯과 같이 그리기
par(mfrow=c(1, 2))
plot(x, y, col="blue", pch=19, cex=2, main="Data")
text(x+0.05, y+0.05, labels=as.character(1:12))
points(x[ind1[1, ]], y[ind1[1, ]], col="orange", pch=19, cex=2)
plot(cutDendro$lower[[11]], yaxt="n", main="Begin building tree")
```


## 덴드로그램 (2)
> 이번에는 2번째로 가까운 점을 찾아보자.

```{r}
# 플롯 준비 : 2번째로 가까운 point 찾기
nextmin = rdist_xy[order(rdist_xy)][3]
ind2 = which(rdist_xy == nextmin, arr.ind=TRUE)
ind2
```


```{r}
# 덴드로그램 : 두 번째 파트 자르기
cutDendro2 = cut(dendro, h=(hcluster$height[2] + 0.00001))
hcluster$height
cutDendro2$lower

par(mfrow=c(1,3))
plot(x, y, col="blue", pch=19, cex=2)
text(x+0.05, y+0.05, labels=as.character(1:12))
points(x[ind1[1, ]], y[ind1[1, ]], col="orange", pch=19, cex=2)
points(x[ind2[1, ]], y[ind2[1, ]], col="red", pch=19, cex=2)
plot(cutDendro2$lower[[10]], yaxt="n")
plot(cutDendro2$lower[[5]], yaxt="n")
```

## 히트맵
> 히트맵을 이용해서 보자.

```{r}
if ("gplots" %in% rownames(installed.packages())) {
  print("설치되어 있음")
} else {
  install.packages("gplots")
}
```

```{r}
# 히트맵으로 보기
library(gplots)
datamat = as.matrix(data.frame(x=x, y=y))
# density.info = none
heatmap.2(datamat, trace='none', notecol = 'black', cellnote=round(datamat, 3), density.info = 'none')
```

```{r}
# row의 덴드로그램 포함
heatmap.2(datamat, trace='none', notecol='black', 
          cellnote=round(datamat, 3), density.info='none', 
          dendrogram="row")
```

```{r}
# col의 덴드로그램 포함
heatmap.2(datamat, trace='none', notecol='black', 
          cellnote=round(datamat, 3),
          density.info='none',
          dendrogram="col")
```


# 예시 2

```{r}
# 거리: 유클리드, linkage: complete
hc1 = hclust(dist(dataFrame))
plot(hc1, main="Euclidean distance/complete")

hc1$height
cut_hc1 = cut(hc1, h = hc1$height[1] + 0.00001)
```

```{r}
# 거리: absolute, linkage: centroid
hc2 <- hclust(dist(dataFrame, method="minkowski", p=1), method="single")
plot(hc2, main="Absolute/Centroid")
```

```{r}
# x만 클러스터링
hClustering2 <- hclust(dist(x))
plot(hClustering2)
```

```{r}
# y만 클러스터링
hClustering3 <- hclust(dist(y))
plot(hClustering3)
```

```{r}
# 정규화
dataFrame2<-scale(dataFrame)
hClustering4 <- hclust(dist(dataFrame2))
plot(hClustering4)
```
